def PROP_TYPE(proptag: int) -> int: ...
def PROP_ID(proptag: int) -> int: ...
def PROP_TYPE_AND_ID(proptag: int) -> int: ...
def PROP_TAG(proptype: int, propid: int) -> int: ...
def CHANGE_PROP_TYPE(proptag: int, proptype: int) -> int: ...
